apiVersion: v1
kind: Service
metadata:
  name: postgres-external-db-service
  labels:
    app: postgres
spec:
  type: ExternalName
  externalName: travel-advisor-db-instance.c9saqwwe4ylw.us-east-2.rds.amazonaws.com
  ports:
    - port: 5432
      targetPort: 5432
